// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: proto/fraud/v1/fraud.proto

package fraudpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FraudDetectionServiceClient is the client API for FraudDetectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudDetectionServiceClient interface {
	EvaluateTransaction(ctx context.Context, in *FraudEvaluationRequest, opts ...grpc.CallOption) (*FraudEvaluationResponse, error)
}

type fraudDetectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudDetectionServiceClient(cc grpc.ClientConnInterface) FraudDetectionServiceClient {
	return &fraudDetectionServiceClient{cc}
}

func (c *fraudDetectionServiceClient) EvaluateTransaction(ctx context.Context, in *FraudEvaluationRequest, opts ...grpc.CallOption) (*FraudEvaluationResponse, error) {
	out := new(FraudEvaluationResponse)
	err := c.cc.Invoke(ctx, "/fraud.v1.FraudDetectionService/EvaluateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudDetectionServiceServer is the server API for FraudDetectionService service.
// All implementations must embed UnimplementedFraudDetectionServiceServer
// for forward compatibility
type FraudDetectionServiceServer interface {
	EvaluateTransaction(context.Context, *FraudEvaluationRequest) (*FraudEvaluationResponse, error)
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

// UnimplementedFraudDetectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFraudDetectionServiceServer struct {
}

func (UnimplementedFraudDetectionServiceServer) EvaluateTransaction(context.Context, *FraudEvaluationRequest) (*FraudEvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateTransaction not implemented")
}
func (UnimplementedFraudDetectionServiceServer) mustEmbedUnimplementedFraudDetectionServiceServer() {}

// UnsafeFraudDetectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudDetectionServiceServer will
// result in compilation errors.
type UnsafeFraudDetectionServiceServer interface {
	mustEmbedUnimplementedFraudDetectionServiceServer()
}

func RegisterFraudDetectionServiceServer(s grpc.ServiceRegistrar, srv FraudDetectionServiceServer) {
	s.RegisterService(&FraudDetectionService_ServiceDesc, srv)
}

func _FraudDetectionService_EvaluateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudDetectionServiceServer).EvaluateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fraud.v1.FraudDetectionService/EvaluateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudDetectionServiceServer).EvaluateTransaction(ctx, req.(*FraudEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudDetectionService_ServiceDesc is the grpc.ServiceDesc for FraudDetectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudDetectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.v1.FraudDetectionService",
	HandlerType: (*FraudDetectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateTransaction",
			Handler:    _FraudDetectionService_EvaluateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fraud/v1/fraud.proto",
}
