// Code generated by mockery v2.53.6. DO NOT EDIT.

package transaction

import (
	context "context"
	pagination "core-banking/pkg/pagination"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *MockRepository) BeginTx(ctx context.Context) (*sqlx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sqlx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sqlx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompleteTransaction provides a mock function with given fields: ctx, txID
func (_m *MockRepository) CompleteTransaction(ctx context.Context, txID string) error {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, txID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreditAccount provides a mock function with given fields: ctx, accountID, amount
func (_m *MockRepository) CreditAccount(ctx context.Context, accountID string, amount int64) error {
	ret := _m.Called(ctx, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreditAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, accountID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DebitAccount provides a mock function with given fields: ctx, accountID, amount
func (_m *MockRepository) DebitAccount(ctx context.Context, accountID string, amount int64) error {
	ret := _m.Called(ctx, accountID, amount)

	if len(ret) == 0 {
		panic("no return value specified for DebitAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, accountID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetIdempotency provides a mock function with given fields: ctx, key
func (_m *MockRepository) GetIdempotency(ctx context.Context, key string) (*IdempotencyKey, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetIdempotency")
	}

	var r0 *IdempotencyKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*IdempotencyKey, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *IdempotencyKey); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IdempotencyKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSenderForUpdate provides a mock function with given fields: ctx, accountID
func (_m *MockRepository) GetSenderForUpdate(ctx context.Context, accountID string) (SenderAccount, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetSenderForUpdate")
	}

	var r0 SenderAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (SenderAccount, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) SenderAccount); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(SenderAccount)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByReferenceID provides a mock function with given fields: ctx, partnerRefNo
func (_m *MockRepository) GetTransactionByReferenceID(ctx context.Context, partnerRefNo string) (*Transaction, error) {
	ret := _m.Called(ctx, partnerRefNo)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByReferenceID")
	}

	var r0 *Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Transaction, error)); ok {
		return rf(ctx, partnerRefNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Transaction); ok {
		r0 = rf(ctx, partnerRefNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partnerRefNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertJournal provides a mock function with given fields: ctx, txID
func (_m *MockRepository) InsertJournal(ctx context.Context, txID string) (string, error) {
	ret := _m.Called(ctx, txID)

	if len(ret) == 0 {
		panic("no return value specified for InsertJournal")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, txID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, txID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, txID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertLedger provides a mock function with given fields: ctx, p
func (_m *MockRepository) InsertLedger(ctx context.Context, p InsertLedgerParams) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertLedger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, InsertLedgerParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertTransaction provides a mock function with given fields: ctx, p
func (_m *MockRepository) InsertTransaction(ctx context.Context, p InsertTransactionParams) (string, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for InsertTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, InsertTransactionParams) (string, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, InsertTransactionParams) string); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, InsertTransactionParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsTransactionExists provides a mock function with given fields: ctx, partnerRefNo
func (_m *MockRepository) IsTransactionExists(ctx context.Context, partnerRefNo string) (bool, error) {
	ret := _m.Called(ctx, partnerRefNo)

	if len(ret) == 0 {
		panic("no return value specified for IsTransactionExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, partnerRefNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, partnerRefNo)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, partnerRefNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f
func (_m *MockRepository) List(ctx context.Context, f TransactionListFilter) ([]TransactionHistoryResponse, int, *pagination.Cursor, *pagination.Cursor, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []TransactionHistoryResponse
	var r1 int
	var r2 *pagination.Cursor
	var r3 *pagination.Cursor
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, TransactionListFilter) ([]TransactionHistoryResponse, int, *pagination.Cursor, *pagination.Cursor, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, TransactionListFilter) []TransactionHistoryResponse); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TransactionHistoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, TransactionListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, TransactionListFilter) *pagination.Cursor); ok {
		r2 = rf(ctx, f)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*pagination.Cursor)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, TransactionListFilter) *pagination.Cursor); ok {
		r3 = rf(ctx, f)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*pagination.Cursor)
		}
	}

	if rf, ok := ret.Get(4).(func(context.Context, TransactionListFilter) error); ok {
		r4 = rf(ctx, f)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// LockReceiver provides a mock function with given fields: ctx, accountID
func (_m *MockRepository) LockReceiver(ctx context.Context, accountID string) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for LockReceiver")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveIdempotency provides a mock function with given fields: ctx, ik
func (_m *MockRepository) SaveIdempotency(ctx context.Context, ik *IdempotencyKey) error {
	ret := _m.Called(ctx, ik)

	if len(ret) == 0 {
		panic("no return value specified for SaveIdempotency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *IdempotencyKey) error); ok {
		r0 = rf(ctx, ik)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *MockRepository) WithTx(tx *sqlx.Tx) Repository {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 Repository
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) Repository); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Repository)
		}
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
