// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: proto/account_information/v1/account_information.proto

package account_informationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountInformationServiceClient is the client API for AccountInformationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountInformationServiceClient interface {
	GetBalance(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	GetLastTransactionAsSource(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetLastTransactionAsBeneficiary(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetAverageAmountLast30Transactions(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AverageAmountResponse, error)
	GetAccountInfo(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountInfoResponse, error)
}

type accountInformationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountInformationServiceClient(cc grpc.ClientConnInterface) AccountInformationServiceClient {
	return &accountInformationServiceClient{cc}
}

func (c *accountInformationServiceClient) GetBalance(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/account_information.v1.AccountInformationService/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationServiceClient) GetLastTransactionAsSource(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/account_information.v1.AccountInformationService/GetLastTransactionAsSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationServiceClient) GetLastTransactionAsBeneficiary(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/account_information.v1.AccountInformationService/GetLastTransactionAsBeneficiary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationServiceClient) GetAverageAmountLast30Transactions(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AverageAmountResponse, error) {
	out := new(AverageAmountResponse)
	err := c.cc.Invoke(ctx, "/account_information.v1.AccountInformationService/GetAverageAmountLast30Transactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountInformationServiceClient) GetAccountInfo(ctx context.Context, in *AccountRequest, opts ...grpc.CallOption) (*AccountInfoResponse, error) {
	out := new(AccountInfoResponse)
	err := c.cc.Invoke(ctx, "/account_information.v1.AccountInformationService/GetAccountInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountInformationServiceServer is the server API for AccountInformationService service.
// All implementations must embed UnimplementedAccountInformationServiceServer
// for forward compatibility
type AccountInformationServiceServer interface {
	GetBalance(context.Context, *AccountRequest) (*GetBalanceResponse, error)
	GetLastTransactionAsSource(context.Context, *AccountRequest) (*TransactionResponse, error)
	GetLastTransactionAsBeneficiary(context.Context, *AccountRequest) (*TransactionResponse, error)
	GetAverageAmountLast30Transactions(context.Context, *AccountRequest) (*AverageAmountResponse, error)
	GetAccountInfo(context.Context, *AccountRequest) (*AccountInfoResponse, error)
	mustEmbedUnimplementedAccountInformationServiceServer()
}

// UnimplementedAccountInformationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountInformationServiceServer struct {
}

func (UnimplementedAccountInformationServiceServer) GetBalance(context.Context, *AccountRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedAccountInformationServiceServer) GetLastTransactionAsSource(context.Context, *AccountRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastTransactionAsSource not implemented")
}
func (UnimplementedAccountInformationServiceServer) GetLastTransactionAsBeneficiary(context.Context, *AccountRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastTransactionAsBeneficiary not implemented")
}
func (UnimplementedAccountInformationServiceServer) GetAverageAmountLast30Transactions(context.Context, *AccountRequest) (*AverageAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAverageAmountLast30Transactions not implemented")
}
func (UnimplementedAccountInformationServiceServer) GetAccountInfo(context.Context, *AccountRequest) (*AccountInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountInfo not implemented")
}
func (UnimplementedAccountInformationServiceServer) mustEmbedUnimplementedAccountInformationServiceServer() {
}

// UnsafeAccountInformationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountInformationServiceServer will
// result in compilation errors.
type UnsafeAccountInformationServiceServer interface {
	mustEmbedUnimplementedAccountInformationServiceServer()
}

func RegisterAccountInformationServiceServer(s grpc.ServiceRegistrar, srv AccountInformationServiceServer) {
	s.RegisterService(&AccountInformationService_ServiceDesc, srv)
}

func _AccountInformationService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_information.v1.AccountInformationService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).GetBalance(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformationService_GetLastTransactionAsSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).GetLastTransactionAsSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_information.v1.AccountInformationService/GetLastTransactionAsSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).GetLastTransactionAsSource(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformationService_GetLastTransactionAsBeneficiary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).GetLastTransactionAsBeneficiary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_information.v1.AccountInformationService/GetLastTransactionAsBeneficiary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).GetLastTransactionAsBeneficiary(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformationService_GetAverageAmountLast30Transactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).GetAverageAmountLast30Transactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_information.v1.AccountInformationService/GetAverageAmountLast30Transactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).GetAverageAmountLast30Transactions(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountInformationService_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountInformationServiceServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_information.v1.AccountInformationService/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountInformationServiceServer).GetAccountInfo(ctx, req.(*AccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountInformationService_ServiceDesc is the grpc.ServiceDesc for AccountInformationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountInformationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account_information.v1.AccountInformationService",
	HandlerType: (*AccountInformationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _AccountInformationService_GetBalance_Handler,
		},
		{
			MethodName: "GetLastTransactionAsSource",
			Handler:    _AccountInformationService_GetLastTransactionAsSource_Handler,
		},
		{
			MethodName: "GetLastTransactionAsBeneficiary",
			Handler:    _AccountInformationService_GetLastTransactionAsBeneficiary_Handler,
		},
		{
			MethodName: "GetAverageAmountLast30Transactions",
			Handler:    _AccountInformationService_GetAverageAmountLast30Transactions_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _AccountInformationService_GetAccountInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account_information/v1/account_information.proto",
}
