version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: core_banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  core-banking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core_banking_api
    depends_on:
      - postgres
    ports:
      - "8120:8120"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: banking
      DB_SSLMODE: disable
    restart: unless-stopped

volumes:
  pgdata:
    name: core_banking_pgdata
