# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.fraud.v1 import fraud_pb2 as proto_dot_fraud_dot_v1_dot_fraud__pb2


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateTransaction = channel.unary_unary(
                '/fraud.v1.FraudDetectionService/EvaluateTransaction',
                request_serializer=proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationRequest.SerializeToString,
                response_deserializer=proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationResponse.FromString,
                )


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateTransaction,
                    request_deserializer=proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationRequest.FromString,
                    response_serializer=proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.v1.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.v1.FraudDetectionService/EvaluateTransaction',
            proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationRequest.SerializeToString,
            proto_dot_fraud_dot_v1_dot_fraud__pb2.FraudEvaluationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
