# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fraud/v1/fraud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/fraud/v1/fraud.proto',
  package='fraud.v1',
  syntax='proto3',
  serialized_options=b'Z\026proto/fraud/v1;fraudpb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aproto/fraud/v1/fraud.proto\x12\x08\x66raud.v1\"f\n\x11\x44\x65viceFingerprint\x12\x12\n\nuser_agent\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\t\x12\x19\n\x11screen_resolution\x18\x03 \x01(\t\x12\x10\n\x08timezone\x18\x04 \x01(\t\"\xd6\x02\n\x16\x46raudEvaluationRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x1c\n\x14partner_reference_no\x18\x02 \x01(\t\x12\x14\n\x0creference_no\x18\x03 \x01(\t\x12\x19\n\x11source_account_no\x18\x04 \x01(\t\x12\x1e\n\x16\x62\x65neficiary_account_no\x18\x05 \x01(\t\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\x12\x11\n\tsource_ip\x18\x08 \x01(\t\x12\x11\n\tdevice_id\x18\t \x01(\t\x12\x37\n\x12\x64\x65vice_fingerprint\x18\n \x01(\x0b\x32\x1b.fraud.v1.DeviceFingerprint\x12\x0f\n\x07\x63hannel\x18\x0b \x01(\t\x12\x10\n\x08latitude\x18\x0c \x01(\x01\x12\x11\n\tlongitude\x18\r \x01(\x01\"\x8f\x01\n\x17\x46raudEvaluationResponse\x12$\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x12.fraud.v1.Decision\x12\x12\n\nrisk_score\x18\x02 \x01(\x01\x12\x17\n\x0ftriggered_rules\x18\x03 \x03(\t\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t*;\n\x08\x44\x65\x63ision\x12\t\n\x05\x41LLOW\x10\x00\x12\r\n\tCHALLENGE\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x12\n\n\x06REVIEW\x10\x03\x32s\n\x15\x46raudDetectionService\x12Z\n\x13\x45valuateTransaction\x12 .fraud.v1.FraudEvaluationRequest\x1a!.fraud.v1.FraudEvaluationResponseB\x18Z\x16proto/fraud/v1;fraudpbb\x06proto3'
)

_DECISION = _descriptor.EnumDescriptor(
  name='Decision',
  full_name='fraud.v1.Decision',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALLOW', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHALLENGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BLOCK', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVIEW', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=635,
  serialized_end=694,
)
_sym_db.RegisterEnumDescriptor(_DECISION)

Decision = enum_type_wrapper.EnumTypeWrapper(_DECISION)
ALLOW = 0
CHALLENGE = 1
BLOCK = 2
REVIEW = 3



_DEVICEFINGERPRINT = _descriptor.Descriptor(
  name='DeviceFingerprint',
  full_name='fraud.v1.DeviceFingerprint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='fraud.v1.DeviceFingerprint.user_agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform', full_name='fraud.v1.DeviceFingerprint.platform', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='screen_resolution', full_name='fraud.v1.DeviceFingerprint.screen_resolution', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='fraud.v1.DeviceFingerprint.timezone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=142,
)


_FRAUDEVALUATIONREQUEST = _descriptor.Descriptor(
  name='FraudEvaluationRequest',
  full_name='fraud.v1.FraudEvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='fraud.v1.FraudEvaluationRequest.transaction_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partner_reference_no', full_name='fraud.v1.FraudEvaluationRequest.partner_reference_no', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_no', full_name='fraud.v1.FraudEvaluationRequest.reference_no', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_account_no', full_name='fraud.v1.FraudEvaluationRequest.source_account_no', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='beneficiary_account_no', full_name='fraud.v1.FraudEvaluationRequest.beneficiary_account_no', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='fraud.v1.FraudEvaluationRequest.amount', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency', full_name='fraud.v1.FraudEvaluationRequest.currency', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_ip', full_name='fraud.v1.FraudEvaluationRequest.source_ip', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='fraud.v1.FraudEvaluationRequest.device_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_fingerprint', full_name='fraud.v1.FraudEvaluationRequest.device_fingerprint', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='fraud.v1.FraudEvaluationRequest.channel', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='fraud.v1.FraudEvaluationRequest.latitude', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='fraud.v1.FraudEvaluationRequest.longitude', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=487,
)


_FRAUDEVALUATIONRESPONSE = _descriptor.Descriptor(
  name='FraudEvaluationResponse',
  full_name='fraud.v1.FraudEvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='decision', full_name='fraud.v1.FraudEvaluationResponse.decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='risk_score', full_name='fraud.v1.FraudEvaluationResponse.risk_score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='triggered_rules', full_name='fraud.v1.FraudEvaluationResponse.triggered_rules', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='fraud.v1.FraudEvaluationResponse.event_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='fraud.v1.FraudEvaluationResponse.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=490,
  serialized_end=633,
)

_FRAUDEVALUATIONREQUEST.fields_by_name['device_fingerprint'].message_type = _DEVICEFINGERPRINT
_FRAUDEVALUATIONRESPONSE.fields_by_name['decision'].enum_type = _DECISION
DESCRIPTOR.message_types_by_name['DeviceFingerprint'] = _DEVICEFINGERPRINT
DESCRIPTOR.message_types_by_name['FraudEvaluationRequest'] = _FRAUDEVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['FraudEvaluationResponse'] = _FRAUDEVALUATIONRESPONSE
DESCRIPTOR.enum_types_by_name['Decision'] = _DECISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceFingerprint = _reflection.GeneratedProtocolMessageType('DeviceFingerprint', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEFINGERPRINT,
  '__module__' : 'proto.fraud.v1.fraud_pb2'
  # @@protoc_insertion_point(class_scope:fraud.v1.DeviceFingerprint)
  })
_sym_db.RegisterMessage(DeviceFingerprint)

FraudEvaluationRequest = _reflection.GeneratedProtocolMessageType('FraudEvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDEVALUATIONREQUEST,
  '__module__' : 'proto.fraud.v1.fraud_pb2'
  # @@protoc_insertion_point(class_scope:fraud.v1.FraudEvaluationRequest)
  })
_sym_db.RegisterMessage(FraudEvaluationRequest)

FraudEvaluationResponse = _reflection.GeneratedProtocolMessageType('FraudEvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDEVALUATIONRESPONSE,
  '__module__' : 'proto.fraud.v1.fraud_pb2'
  # @@protoc_insertion_point(class_scope:fraud.v1.FraudEvaluationResponse)
  })
_sym_db.RegisterMessage(FraudEvaluationResponse)


DESCRIPTOR._options = None

_FRAUDDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='FraudDetectionService',
  full_name='fraud.v1.FraudDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=696,
  serialized_end=811,
  methods=[
  _descriptor.MethodDescriptor(
    name='EvaluateTransaction',
    full_name='fraud.v1.FraudDetectionService.EvaluateTransaction',
    index=0,
    containing_service=None,
    input_type=_FRAUDEVALUATIONREQUEST,
    output_type=_FRAUDEVALUATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRAUDDETECTIONSERVICE)

DESCRIPTOR.services_by_name['FraudDetectionService'] = _FRAUDDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
