// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1.0/transfer-intrabank": {
            "post": {
                "description": "Execute an intrabank fund transfer (SNAP Service Code 17)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transfer"
                ],
                "summary": "Intrabank Transfer",
                "parameters": [
                    {
                        "type": "string",
                        "default": "2026-04-15T10:00:00+07:00",
                        "description": "Request timestamp",
                        "name": "X-TIMESTAMP",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "PLACEHOLDER",
                        "description": "Digital signature",
                        "name": "X-SIGNATURE",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "PJP-001",
                        "description": "Partner ID",
                        "name": "X-PARTNER-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "ext-transfer-001",
                        "description": "External ID (idempotency)",
                        "name": "X-EXTERNAL-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "CH001",
                        "description": "Channel ID",
                        "name": "CHANNEL-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Transfer payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transfer.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "transfer.AccountField": {
            "type": "object",
            "required": [
                "accountNo"
            ],
            "properties": {
                "accountNo": {
                    "type": "string",
                    "example": "8001234567890123"
                }
            }
        },
        "transfer.AmountField": {
            "type": "object",
            "required": [
                "currency",
                "value"
            ],
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "IDR"
                },
                "value": {
                    "type": "string",
                    "example": "150000.00"
                }
            }
        },
        "transfer.TransferRequest": {
            "type": "object",
            "required": [
                "amount",
                "beneficiaryAccount",
                "partnerReferenceNo",
                "sourceAccount"
            ],
            "properties": {
                "additionalInfo": {},
                "amount": {
                    "$ref": "#/definitions/transfer.AmountField"
                },
                "beneficiaryAccount": {
                    "$ref": "#/definitions/transfer.AccountField"
                },
                "feeType": {
                    "type": "string",
                    "enum": [
                        "OUR",
                        "BEN",
                        "SHA"
                    ],
                    "example": "OUR"
                },
                "partnerReferenceNo": {
                    "type": "string",
                    "example": "202311010000000000002"
                },
                "remark": {
                    "type": "string",
                    "example": "Lunch at Warung Ikan Bakar"
                },
                "sourceAccount": {
                    "$ref": "#/definitions/transfer.AccountField"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Payment Initiation Acquiring Service API",
	Description:      "API for intrabank fund transfers (PJP)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
