services:
  # ─────────────────────────────────────────────
  #  Data Stores
  # ─────────────────────────────────────────────
  postgres:
    image: postgres:15
    container_name: pjp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pjp-network

  redis:
    image: redis:7-alpine
    container_name: pjp_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pjp-network

  # ─────────────────────────────────────────────
  #  Messaging
  # ─────────────────────────────────────────────
  controller-1:
    image: apache/kafka:latest
    container_name: controller-1
    hostname: controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    networks:
      - pjp-network

  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    ports:
      - '${KAFKA_EXTERNAL_PORT}:9094'
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:9092,EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT}'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - pjp-network
    depends_on:
      - controller-1

  kafka-init-topics:
    image: apache/kafka:latest
    container_name: kafka_init_topics
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - pjp-network
    command: |
      sh -c "
      echo 'Waiting for Kafka to be ready...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:9092 --list
      echo 'Creating topics...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:9092 --create --if-not-exists --topic account_created_v1 --replication-factor 1 --partitions 3
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:9092 --create --if-not-exists --topic transfer_completed_v1 --replication-factor 1 --partitions 3
      echo 'Topics created.'
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: pjp_kafka_ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: pjp-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "broker:9092"
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - pjp-network

  # ─────────────────────────────────────────────
  #  Observability
  # ─────────────────────────────────────────────

  loki:
    image: grafana/loki:2.9.0
    container_name: pjp_loki
    volumes:
      - ./observability/loki.yml:/etc/loki/local-config.yaml
    ports:
      - "${LOKI_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - pjp-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  tempo:
    image: grafana/tempo:2.9.0
    container_name: pjp_tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo.yml:/etc/tempo.yaml
    ports:
      - "${TEMPO_PORT}:3200"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    restart: unless-stopped
    networks:
      - pjp-network

  grafana:
    image: grafana/grafana:latest
    container_name: pjp_grafana
    volumes:
      - ./observability/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - loki
      - tempo
    restart: unless-stopped
    networks:
      - pjp-network

  # ─────────────────────────────────────────────
  #  Application Services
  # ─────────────────────────────────────────────
  core-banking-system:
    build:
      context: .
      dockerfile: ./services/core-banking-system/Dockerfile
    container_name: pjp_core_banking
    depends_on:
      postgres:
        condition: service_healthy
      loki:
        condition: service_healthy
    ports:
      - "${CBS_GRPC_PORT}:50052"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      GRPC_PORT: ":50052"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      LOKI_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped
    networks:
      - pjp-network

  account-issuance:
    build:
      context: .
      dockerfile: ./services/account-issuance-service/Dockerfile
    container_name: pjp_account_issuance
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      core-banking-system:
        condition: service_started
      loki:
        condition: service_healthy
    ports:
      - "${AINS_HTTP_PORT}:8080"
      - "${AINS_GRPC_PORT}:50051"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      KAFKA_BROKERS: "broker:9092"
      CBS_GRPC_ADDR: "core-banking-system:50052"
      GRPC_PORT: ":50051"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      LOKI_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped 
    networks:
      - pjp-network

  payment-initiation:
    build:
      context: .
      dockerfile: ./services/payment-initiation-acquiring-service/Dockerfile
    container_name: pjp_payment_initiation
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy
      account-issuance:
        condition: service_started
      core-banking-system:
        condition: service_started
      fraud-detection:
        condition: service_started
      loki:
        condition: service_healthy
    ports:
      - "${PIAS_HTTP_PORT}:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      KAFKA_BROKERS: "broker:9092"
      AIS_GRPC_ADDR: "account-issuance:50051"
      CBS_GRPC_ADDR: "core-banking-system:50052"
      FRAUD_HTTP_ADDR: "fraud-detection:8085"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      LOKI_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped
    networks:
      - pjp-network

  fraud-detection:
    build:
      context: .
      dockerfile: ./services/fraud-detection-service/Dockerfile
    container_name: pjp_fraud_detection
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${FRAUD_HTTP_PORT:-8085}:8085"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      HTTP_PORT: "8085"
      AIS_GRPC_ADDR: "account-information:50055"
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      LOKI_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped
    networks:
      - pjp-network

  account-information:
    build:
      context: .
      dockerfile: ./services/account-information-service/Dockerfile
    container_name: pjp_account_information
    depends_on:
      postgres:
        condition: service_healthy
      broker:
        condition: service_healthy
      loki:
        condition: service_healthy
    ports:
      - "${AIS_HTTP_PORT:-8081}:8081"
      - "${AIS_GRPC_PORT:-50055}:50055"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      KAFKA_BROKERS: "broker:9092"
      GRPC_PORT: ":50055"
      HTTP_PORT: ":8081"
    restart: unless-stopped
    networks:
      - pjp-network

  notification:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    container_name: pjp_notification
    depends_on:
      postgres:
        condition: service_healthy
      broker:
        condition: service_healthy
      loki:
        condition: service_healthy
    ports:
      - "${NS_HTTP_PORT}:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: ${DB_SSLMODE}
      KAFKA_BROKERS: "broker:9092"
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      KAFKA_TOPICS: "account_created_v1,transfer_completed_v1"
      WEBHOOK_URL: ${WEBHOOK_URL}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      LOKI_URL: http://loki:3100/loki/api/v1/push
    restart: unless-stopped
    networks:
      - pjp-network

volumes:
  pgdata:
    name: pjp_pgdata
  redisdata:
    name: pjp_redisdata
  # kafkadata:
  #   name: pjp_kafkadata

networks:
  pjp-network:
    name: pjp-network
    driver: bridge
