// Code generated by mockery v2.53.6. DO NOT EDIT.

package account

import (
	context "context"
	pagination "core-banking/pkg/pagination"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, acc
func (_m *MockRepository) Create(ctx context.Context, acc *Account) error {
	ret := _m.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Account) error); ok {
		r0 = rf(ctx, acc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id string) (*Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, f
func (_m *MockRepository) List(ctx context.Context, f ListFilter) ([]Account, int, *pagination.Cursor, *pagination.Cursor, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Account
	var r1 int
	var r2 *pagination.Cursor
	var r3 *pagination.Cursor
	var r4 error
	if rf, ok := ret.Get(0).(func(context.Context, ListFilter) ([]Account, int, *pagination.Cursor, *pagination.Cursor, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ListFilter) []Account); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ListFilter) int); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ListFilter) *pagination.Cursor); ok {
		r2 = rf(ctx, f)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*pagination.Cursor)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context, ListFilter) *pagination.Cursor); ok {
		r3 = rf(ctx, f)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(*pagination.Cursor)
		}
	}

	if rf, ok := ret.Get(4).(func(context.Context, ListFilter) error); ok {
		r4 = rf(ctx, f)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockRepository) UpdateStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *MockRepository) GetBalance(ctx context.Context, accountID string) (*AccountBalance, error) {
	ret := _m.Called(ctx, accountID)
	return ret.Get(0).(*AccountBalance), ret.Error(1)
}

func (_m *MockRepository) UpdateBalance(ctx context.Context, accountID string, amount int64) error {
	ret := _m.Called(ctx, accountID, amount)
	return ret.Error(0)
}

func (_m *MockRepository) GetProduct(ctx context.Context, code string) (*Product, error) {
	ret := _m.Called(ctx, code)
	return ret.Get(0).(*Product), ret.Error(1)
}

func (_m *MockRepository) GetCustomerByID(ctx context.Context, id string) (*Customer, error) {
	ret := _m.Called(ctx, id)
	return ret.Get(0).(*Customer), ret.Error(1)
}

func (_m *MockRepository) CreateCustomer(ctx context.Context, cust *Customer) error {
	ret := _m.Called(ctx, cust)
	return ret.Error(0)
}

func (_m *MockRepository) UpdateCustomer(ctx context.Context, cust *Customer) error {
	ret := _m.Called(ctx, cust)
	return ret.Error(0)
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
